services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
      - ./thumbnails:/app/thumbnails

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
      - ./thumbnails:/app/thumbnails
      